//! Keyboard/mouse work with graph
//! 

use std::fmt::Debug;

use egui::{InputState, PointerButton, Response};
#[cfg(feature="egui-probe")]
use egui_probe::EguiProbe;
#[cfg(feature="serde")]
use serde::{Deserialize, Serialize};

///An input event generated by the integration.
pub trait GraphEvents {
    /// Remove hovered wire by second click
    fn remove_hovered_wire(
        &mut self,
        background_response: &Response,
        input_state: &InputState,
    ) -> bool {
        background_response.clicked_by(PointerButton::Secondary)
    }

    /// Start select area
    fn start_select_area(
        &mut self,
        background_response: &Response,
        input_state: &InputState,
    ) -> bool {
        background_response.drag_started_by(PointerButton::Primary) && input_state.modifiers.shift
    }

    /// Stop select area
    fn stop_select_area(
        &mut self,
        background_response: &Response,
        input_state: &InputState,
    ) -> bool {
        background_response.drag_stopped_by(PointerButton::Primary)
    }

    /// Move area by
    fn move_area(&mut self, background_response: &Response, input_state: &InputState) -> bool {
        background_response.dragged_by(PointerButton::Primary)
    }

    /// Cancel new wire
    fn cancel_new_wire(
        &mut self,
        background_response: &Response,
        input_state: &InputState,
    ) -> bool {
        input_state.pointer.button_down(PointerButton::Secondary)
    }

    ///Do centering
    fn do_centering(&mut self, background_response: &Response, input_state: &InputState) -> bool {
        background_response.double_clicked()
    }

    ///Deselect all nodes
    fn deselect_all_nodes(
        &mut self,
        background_response: &Response,
        input_state: &InputState,
    ) -> bool {
        input_state.modifiers.command && background_response.clicked_by(PointerButton::Primary)
    }

    /// Node move
    fn node_move(&mut self, response: &Response, input_state: &InputState) -> bool {
        !input_state.modifiers.shift
            && !input_state.modifiers.command
            && response.dragged_by(PointerButton::Primary)
    }

    /// Select one node
    fn select_one_node(&mut self, response: &Response, input_state: &InputState) -> bool {
        (response.clicked_by(PointerButton::Primary) || response.dragged_by(PointerButton::Primary))
            && input_state.modifiers.shift
    }

    /// Deselect one node
    fn deselect_one_node(&mut self, response: &Response, input_state: &InputState) -> bool {
        (response.clicked_by(PointerButton::Primary) || response.dragged_by(PointerButton::Primary))
            && input_state.modifiers.command
    }

    /// Node to top
    fn not_to_top(&mut self, response: &Response, input_state: &InputState) -> bool {
        response.clicked() || response.dragged() 
    }

    /// Remove or drop new node
    fn remove_wire(&mut self, response: &Response, input_state: &InputState) -> bool {
        response.clicked_by(PointerButton::Secondary)
    }

    ///Start drag wire
    fn start_drag_wire(&mut self, response: &Response, input_state: &InputState) -> bool {
        response.drag_started_by(PointerButton::Primary)
    }

    ///Stop drag wire
    fn stop_drag_wire(&mut self, response: &Response, input_state: &InputState) -> bool {
        response.drag_stopped()
    }
}

/// Default Egui-Snarl keybindings
#[derive(Debug, PartialEq, Default)]
#[cfg_attr(feature="serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "egui-probe", derive(egui_probe::EguiProbe))]
pub struct DefaultGraphEvents {}

impl GraphEvents for DefaultGraphEvents {}
impl GraphEventsExtend for DefaultGraphEvents {}

#[cfg(all(feature = "serde", not(feature = "egui-probe")))]
/// Trait GraphEvents with feature 
pub trait GraphEventsExtend : GraphEvents + Deserialize + Serialize {}

#[cfg(all(not(feature = "serde"), feature = "egui-probe"))]
/// Trait GraphEvents with feature 
pub trait GraphEventsExtend : GraphEvents + EguiProbe{}



#[cfg(all(feature = "serde", feature = "egui-probe"))]
/// Trait GraphEvents with feature 
pub trait GraphEventsExtend: GraphEvents  + Serialize + EguiProbe {}

#[cfg(all(not(feature = "serde"), not(feature = "egui-probe")))]
/// Trait GraphEvents with feature 
pub trait GraphEventsExtend : GraphEvents{}



/// Click and move wire
#[derive(Debug, PartialEq, Default)]
#[cfg_attr(feature="serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "egui-probe", derive(egui_probe::EguiProbe))]
pub struct ClickGraphEvents{
    drag_wire: bool
}

impl GraphEvents for ClickGraphEvents{
    fn start_drag_wire(&mut self, response: &Response, input_state: &InputState) -> bool {
        if !self.drag_wire && response.clicked_by(PointerButton::Primary){
            self.drag_wire = true;
        }
        self.drag_wire
    }

    fn stop_drag_wire(&mut self, response: &Response, input_state: &InputState) -> bool {
        if self.drag_wire && response.clicked_by(PointerButton::Primary){
            self.drag_wire = false;
        } 
        !self.drag_wire
    }
}

impl GraphEventsExtend for ClickGraphEvents{}